export const recommendations = [

  {
    '': 0,
    Priority: 'High',
    Contact: 'O. O. C. Cooper',
    Postcode: 'OX14 5NJ',
    Messaging: 'Call',
    Suggestion: 'Consider unbranded messaging',
    Reason: 'Anatoxidone is being outperformed by drugs outside its category.',
    Target: 'yes',
    Access: 'easy',
    Potential: 56,
  },
  {
    '': 1,
    Priority: 'Mid',
    Contact: 'L. C. B. Khan',
    Postcode: 'GU4 8NE',
    Messaging: 'Meeting',
    Suggestion: 'Consider branded messaging',
    Reason: 'Edoxidone is the top performing drug in this category',
    Target: 'No',
    Access: 'mid',
    Potential: 78,
  },
  {
    '': 2,
    Priority: 'Low',
    Contact: 'J. F. M. Williams',
    Postcode: 'BS27 3TJ',
    Messaging: 'Call',
    Suggestion: 'Virtual rep call recommended',
    Reason: 'Previous face to face attempts unsuccessful',
    Target: 'yes',
    Access: 'hard',
    Potential: 34,
  },
  {
    '': 3,
    Priority: 'High',
    Contact: 'C. Murphy',
    Postcode: 'CF5 1EQ',
    Messaging: 'Meeting',
    Suggestion: 'Consider unbranded messaging',
    Reason: 'Anatoxidone is being outperformed by drugs outside its category',
    Target: 'No',
    Access: 'easy',
    Potential: 56,
  },
  {
    '': 4,
    Priority: 'Mig',
    Contact: 'A. V. Davis',
    Postcode: 'WF4 6DF',
    Messaging: 'Email',
    Suggestion: 'Refer to CCG level',
    Reason: 'Anatoxidone is not on the formulary',
    Target: 'yes',
    Access: 'mid',
    Potential: 46,
  },
  {
    '': 5,
    Priority: 'Low',
    Contact: 'J. W. T. Nasir',
    Postcode: 'SA33 4QU',
    Messaging: 'Call',
    Suggestion: 'Virtual rep call recommended',
    Reason: 'Previous face to face attempts unsuccessful',
    Target: 'No',
    Access: 'hard',
    Potential: 34,
  },
  {
    '': 6,
    Priority: 'High',
    Contact: 'R. X. Wilson',
    Postcode: 'HU6 7JH',
    Messaging: 'Meeting',
    Suggestion: 'Consider branded messaging',
    Reason: 'Roxidone is the top performing drug in this category',
    Target: 'yes',
    Access: 'easy',
    Potential: 26,
  },
  {
    '': 7,
    Priority: 'Mid',
    Contact: 'E. O. Murphy',
    Postcode: 'BS25 1PT',
    Messaging: 'Email',
    Suggestion: 'Consider branded messaging',
    Reason: 'Dabigoxidone is the top performing drug in this category',
    Target: 'No',
    Access: 'mid',
    Potential: 46,
  },
  {
    '': 8,
    Priority: 'Low',
    Contact: 'H. K. Carter',
    Postcode: 'G52 2HJ',
    Messaging: 'Call',
    Suggestion: 'Virtual rep call recommended',
    Reason: 'Previous face to face attempts unsuccessful',
    Target: 'yes',
    Access: 'hard',
    Potential: 57,
  },
  {
    '': 9,
    Priority: 'High',
    Contact: 'G. Rivera',
    Postcode: 'B61 0RY',
    Messaging: 'Call',
    Suggestion: 'Consider unbranded messaging',
    Reason: 'Anatoxidone is being outperformed by drugs outside its category',
    Target: 'yes',
    Access: 'easy',
    Potential: 56,
  },
  {
    '': 10,
    Priority: 'Mid',
    Contact: 'Y. X. Williams',
    Postcode: 'ST6 8GN',
    Messaging: 'Meeting',
    Suggestion: 'Consider branded messaging',
    Reason: 'Edoxidone is the top performing drug in this category',
    Target: 'No',
    Access: 'mid',
    Potential: 78,
  },
  {
    '': 11,
    Priority: 'Low',
    Contact: 'A. M. Wilson',
    Postcode: 'NG5 8AY',
    Messaging: 'Call',
    Suggestion: 'Virtual rep call recommended',
    Reason: 'Previous face to face attempts unsuccessful',
    Target: 'yes',
    Access: 'hard',
    Potential: 34,
  },
  {
    '': 12,
    Priority: 'High',
    Contact: 'S. P. Williams',
    Postcode: 'S61 2TR',
    Messaging: 'Meeting',
    Suggestion: 'Consider unbranded messaging',
    Reason: 'Anatoxidone is being outperformed by drugs outside its category',
    Target: 'No',
    Access: 'easy',
    Potential: 56,
  },
  {
    '': 13,
    Priority: 'Mig',
    Contact: 'N. G. H. Singh',
    Postcode: 'SA4 3QY',
    Messaging: 'Email',
    Suggestion: 'Refer to CCG level',
    Reason: 'Anatoxidone is not on the formulary',
    Target: 'yes',
    Access: 'mid',
    Potential: 46,
  },
  {
    '': 14,
    Priority: 'Low',
    Contact: 'X. Y. C. Patchouli',
    Postcode: 'KA1 1TH',
    Messaging: 'Call',
    Suggestion: 'Virtual rep call recommended',
    Reason: 'Previous face to face attempts unsuccessful',
    Target: 'No',
    Access: 'hard',
    Potential: 34,
  },
  {
    '': 15,
    Priority: 'High',
    Contact: 'X. J. Rivera',
    Postcode: 'NW1 9DB',
    Messaging: 'Meeting',
    Suggestion: 'Consider branded messaging',
    Reason: 'Roxidone is the top performing drug in this category',
    Target: 'yes',
    Access: 'easy',
    Potential: 26,
  },
  {
    '': 16,
    Priority: 'Mid',
    Contact: 'P. Patchouli',
    Postcode: 'AB23 8QU',
    Messaging: 'Email',
    Suggestion: 'Consider branded messaging',
    Reason: 'Dabigoxidone is the top performing drug in this category',
    Target: 'No',
    Access: 'mid',
    Potential: 46,
  },
  {
    '': 17,
    Priority: 'Low',
    Contact: 'W. Cook',
    Postcode: 'W1T 6LA',
    Messaging: 'Call',
    Suggestion: 'Virtual rep call recommended',
    Reason: 'Previous face to face attempts unsuccessful',
    Target: 'yes',
    Access: 'hard',
    Potential: 57,
  },
  {
    '': 18,
    Priority: 'High',
    Contact: 'R. Wilson',
    Postcode: 'E8 2FA',
    Messaging: 'Call',
    Suggestion: 'Consider unbranded messaging',
    Reason: 'Anatoxidone is being outperformed by drugs outside its category',
    Target: 'yes',
    Access: 'easy',
    Potential: 56,
  },
  {
    '': 19,
    Priority: 'Mid',
    Contact: 'D. Z. M. Cook',
    Postcode: 'CB8 9RH',
    Messaging: 'Meeting',
    Suggestion: 'Consider branded messaging',
    Reason: 'Edoxidone is the top performing drug in this category',
    Target: 'No',
    Access: 'mid',
    Potential: 78,
  },
  {
    '': 20,
    Priority: 'Low',
    Contact: 'W. D. Cooper',
    Postcode: 'TN29 0DU',
    Messaging: 'Call',
    Suggestion: 'Virtual rep call recommended',
    Reason: 'Previous face to face attempts unsuccessful',
    Target: 'yes',
    Access: 'hard',
    Potential: 34,
  },
  {
    '': 21,
    Priority: 'High',
    Contact: 'O. Z. W. Singh',
    Postcode: 'AL3 5QY',
    Messaging: 'Meeting',
    Suggestion: 'Consider unbranded messaging',
    Reason: 'Anatoxidone is being outperformed by drugs outside its category',
    Target: 'No',
    Access: 'easy',
    Potential: 56,
  },
  {
    '': 22,
    Priority: 'Mig',
    Contact: 'F. Janssen',
    Postcode: 'LN4 1AU',
    Messaging: 'Email',
    Suggestion: 'Refer to CCG level',
    Reason: 'Anatoxidone is not on the formulary',
    Target: 'yes',
    Access: 'mid',
    Potential: 46,
  },
  {
    '': 23,
    Priority: 'Low',
    Contact: 'V. N. Williams',
    Postcode: 'BL9 9GF',
    Messaging: 'Call',
    Suggestion: 'Virtual rep call recommended',
    Reason: 'Previous face to face attempts unsuccessful',
    Target: 'No',
    Access: 'hard',
    Potential: 34,
  },
  {
    '': 24,
    Priority: 'High',
    Contact: 'V. Khan',
    Postcode: 'SA68 0SH',
    Messaging: 'Meeting',
    Suggestion: 'Consider branded messaging',
    Reason: 'Roxidone is the top performing drug in this category',
    Target: 'yes',
    Access: 'easy',
    Potential: 26,
  },
  {
    '': 25,
    Priority: 'Mid',
    Contact: 'H. R. O. Cook',
    Postcode: 'GL14 1LW',
    Messaging: 'Email',
    Suggestion: 'Consider branded messaging',
    Reason: 'Dabigoxidone is the top performing drug in this category',
    Target: 'No',
    Access: 'mid',
    Potential: 46,
  },
  {
    '': 26,
    Priority: 'Low',
    Contact: 'Y. H. Singh',
    Postcode: 'PR9 9BN',
    Messaging: 'Call',
    Suggestion: 'Virtual rep call recommended',
    Reason: 'Previous face to face attempts unsuccessful',
    Target: 'yes',
    Access: 'hard',
    Potential: 57,
  },
  {
    '': 27,
    Priority: 'High',
    Contact: 'P. Johnson',
    Postcode: 'G21 1XN',
    Messaging: 'Call',
    Suggestion: 'Consider unbranded messaging',
    Reason: 'Anatoxidone is being outperformed by drugs outside its category',
    Target: 'yes',
    Access: 'easy',
    Potential: 56,
  },
  {
    '': 28,
    Priority: 'Mid',
    Contact: 'L. Z. Z. Johnson',
    Postcode: 'G12 9JW',
    Messaging: 'Meeting',
    Suggestion: 'Consider branded messaging',
    Reason: 'Edoxidone is the top performing drug in this category',
    Target: 'No',
    Access: 'mid',
    Potential: 78,
  },
  {
    '': 29,
    Priority: 'Low',
    Contact: 'D. Z. P. Wilson',
    Postcode: 'PE6 8JE',
    Messaging: 'Call',
    Suggestion: 'Virtual rep call recommended',
    Reason: 'Previous face to face attempts unsuccessful',
    Target: 'yes',
    Access: 'hard',
    Potential: 34,
  },
  {
    '': 30,
    Priority: 'High',
    Contact: 'E. Lewis',
    Postcode: 'RH12 5QQ',
    Messaging: 'Meeting',
    Suggestion: 'Consider unbranded messaging',
    Reason: 'Anatoxidone is being outperformed by drugs outside its category',
    Target: 'No',
    Access: 'easy',
    Potential: 56,
  },
  {
    '': 31,
    Priority: 'Mid',
    Contact: 'N. Murphy',
    Postcode: 'CV36 4HT',
    Messaging: 'Email',
    Suggestion: 'Refer to CCG level',
    Reason: 'Anatoxidone is not on the formulary',
    Target: 'yes',
    Access: 'mid',
    Potential: 46,
  },
  {
    '': 32,
    Priority: 'Low',
    Contact: 'D. K. V. Williams',
    Postcode: 'KA2 9DH',
    Messaging: 'Call',
    Suggestion: 'Virtual rep call recommended',
    Reason: 'Previous face to face attempts unsuccessful',
    Target: 'No',
    Access: 'hard',
    Potential: 34,
  },
  {
    '': 33,
    Priority: 'High',
    Contact: 'D. Powell',
    Postcode: 'SY5 6AS',
    Messaging: 'Meeting',
    Suggestion: 'Consider branded messaging',
    Reason: 'Roxidone is the top performing drug in this category',
    Target: 'yes',
    Access: 'easy',
    Potential: 26,
  },
  {
    '': 34,
    Priority: 'Mid',
    Contact: 'H. Johnson',
    Postcode: 'NR31 8ST',
    Messaging: 'Email',
    Suggestion: 'Consider branded messaging',
    Reason: 'Dabigoxidone is the top performing drug in this category',
    Target: 'No',
    Access: 'mid',
    Potential: 46,
  },
  {
    '': 35,
    Priority: 'Low',
    Contact: 'N. Carter',
    Postcode: 'WN2 5LA',
    Messaging: 'Call',
    Suggestion: 'Virtual rep call recommended',
    Reason: 'Previous face to face attempts unsuccessful',
    Target: 'yes',
    Access: 'hard',
    Potential: 57,
  },

];
